[Flight] Don't try to close debug channel twice
When the debug channel was already closed, we must not try to close it
again when the Response gets garbage collected.

Test plan:

1. reduce the Flight fixture App component to a minimum
    - remove everything from `<body>`
    - delete the `console.log` statement
2. open the app in Firefox (seems to have a more aggressive GC strategy)
3. wait a few seconds

On `main`, you will see the following error in the browser console:

```
TypeError: Can not close stream after closing or error
```

With this change, the error is gone.

It's a bit concerning that step 1 is needed to reproduce the issue.
Either GC is behaving differently with the unmodified App, or we may
hold on to the Response under certain conditions, potentially creating
a memory leak. This needs further investigation.