[Fizz] Support `useMemoCache` in renderers with support for Client APIs
Mainly an oversight since we don't have types based off of feature flags.
Now that `enableUseMemoCache` is shipped, `useMemoCache` can be non-nullable.

Discovered during integration testing with Next.js where SSR threw with `TypeError: dispatcher.useMemoCache is not a function` but ultimately recovered due to client-side rendering.